from typing import Dict, Sequence

import numpy as np
import tree
from typing_extensions import override

from openpi_client import base_policy as _base_policy


class ActionChunkBroker(_base_policy.BasePolicy):
    """Wrap a policy and return one action from each generated chunk."""

    def __init__(self, policy: _base_policy.BasePolicy, action_horizon: int):
        self._policy = policy
        self._action_horizon = action_horizon
        self._cur_step = 0
        self._last_results: Dict[str, np.ndarray] | None = None

    @override
    def infer(self, obs: Dict) -> Dict:  # noqa: UP006
        if self._last_results is None:
            self._last_results = self._policy.infer(obs)
            self._cur_step = 0

        def slicer(x):
            return x[self._cur_step, ...] if isinstance(x, np.ndarray) else x

        results = tree.map_structure(slicer, self._last_results)
        self._cur_step += 1
        if self._cur_step >= self._action_horizon:
            self._last_results = None
        return results

    @override
    def reset(self) -> None:
        self._policy.reset()
        self._last_results = None
        self._cur_step = 0


class ForceReflexActionChunkBroker(_base_policy.BasePolicy):
    """Execute a nominal chunk with one force-conditioned joint correction per step.

    The wrapped policy supports two request modes:

    * a normal request generates a nominal VLA action chunk;
    * ``fra_mode=True`` runs only the lightweight Force Reflex Adapter.

    This keeps VLA planning at chunk rate while applying the latest force feedback
    at control rate. The arm command is clipped to optional robot joint limits;
    the gripper command remains exactly as generated by the nominal policy.
    """

    def __init__(
        self,
        policy: _base_policy.BasePolicy,
        action_horizon: int,
        *,
        arm_joint_dim: int = 7,
        force_dim: int = 6,
        force_history_len: int = 64,
        state_key: str = "observation/state",
        force_key: str = "force",
        action_key: str = "actions",
        joint_lower_limits: Sequence[float] | np.ndarray | None = None,
        joint_upper_limits: Sequence[float] | np.ndarray | None = None,
    ):
        if action_horizon <= 0:
            raise ValueError("action_horizon must be positive.")
        if arm_joint_dim <= 0:
            raise ValueError("arm_joint_dim must be positive.")
        if force_dim <= 0 or force_history_len <= 0:
            raise ValueError("force_dim and force_history_len must be positive.")

        self._policy = policy
        self._action_horizon = int(action_horizon)
        self._arm_joint_dim = int(arm_joint_dim)
        self._force_dim = int(force_dim)
        self._force_history_len = int(force_history_len)
        self._state_key = state_key
        self._force_key = force_key
        self._action_key = action_key
        self._joint_lower_limits = self._validate_limits(joint_lower_limits, "joint_lower_limits")
        self._joint_upper_limits = self._validate_limits(joint_upper_limits, "joint_upper_limits")
        if (self._joint_lower_limits is None) != (self._joint_upper_limits is None):
            raise ValueError("joint_lower_limits and joint_upper_limits must be provided together.")
        if (
            self._joint_lower_limits is not None
            and self._joint_upper_limits is not None
            and np.any(self._joint_lower_limits >= self._joint_upper_limits)
        ):
            raise ValueError("Every lower joint limit must be smaller than its upper limit.")

        self._nominal_chunk: np.ndarray | None = None
        self._cur_step = 0
        self._plan_count = 0
        self._force_history: np.ndarray | None = None

    def _validate_limits(self, values, name: str):
        if values is None:
            return None
        array = np.asarray(values, dtype=np.float64)
        if array.shape != (self._arm_joint_dim,) or not np.all(np.isfinite(array)):
            raise ValueError(f"{name} must contain {self._arm_joint_dim} finite values.")
        return array

    def _current_state(self, obs: Dict) -> np.ndarray:
        if self._state_key not in obs:
            raise KeyError(f"FRA requires observation key {self._state_key!r}.")
        state = np.asarray(obs[self._state_key])
        if state.ndim != 1 or state.shape[0] < self._arm_joint_dim:
            raise ValueError(
                f"Observation {self._state_key!r} must be a vector with at least "
                f"{self._arm_joint_dim} joint values."
            )
        return state

    def _current_force(self, obs: Dict, state: np.ndarray) -> np.ndarray:
        if self._force_key in obs:
            force = np.asarray(obs[self._force_key])
        else:
            force_start = self._arm_joint_dim + 1
            force = state[force_start : force_start + self._force_dim]
        if force.shape != (self._force_dim,) or not np.all(np.isfinite(force)):
            raise ValueError(
                f"FRA force must have shape ({self._force_dim},); provide {self._force_key!r} "
                "or append wrench values after arm joints and gripper in observation/state."
            )
        return force

    def _update_force_history(self, force: np.ndarray) -> None:
        if self._force_history is None:
            self._force_history = np.repeat(force[None, :], self._force_history_len, axis=0)
        else:
            self._force_history = np.concatenate([self._force_history[1:], force[None, :]], axis=0)

    def _request_nominal_chunk(self, obs: Dict) -> None:
        planning_obs = dict(obs)
        planning_obs["force_history_global"] = self._force_history
        results = self._policy.infer(planning_obs)
        if self._action_key not in results:
            raise KeyError(f"FRA requires policy output key {self._action_key!r}.")
        actions = np.asarray(results[self._action_key])
        if actions.ndim != 2 or actions.shape[0] < self._action_horizon:
            raise ValueError("The nominal action chunk must have shape [horizon, action_dim].")
        if actions.shape[1] < self._arm_joint_dim:
            raise ValueError("The nominal action dimension is smaller than arm_joint_dim.")
        self._nominal_chunk = actions
        self._cur_step = 0
        self._plan_count += 1

    @override
    def infer(self, obs: Dict) -> Dict:  # noqa: UP006
        if bool(np.asarray(obs.get("reset", False))):
            self._nominal_chunk = None
            self._cur_step = 0
            self._plan_count = 0
            self._force_history = None

        state = self._current_state(obs)
        force = self._current_force(obs, state)
        self._update_force_history(force)
        if self._nominal_chunk is None:
            self._request_nominal_chunk(obs)

        assert self._nominal_chunk is not None
        nominal_action = self._nominal_chunk[self._cur_step]
        previous_index = max(self._cur_step - 1, 0)
        previous_nominal_action = self._nominal_chunk[previous_index]
        reflex_obs = {
            **obs,
            "fra_mode": True,
            "fra_nominal_action": nominal_action,
            "fra_previous_nominal_action": previous_nominal_action,
            "fra_current_joint_state": state[: self._arm_joint_dim],
            "fra_chunk_progress": np.asarray(
                [self._cur_step / self._action_horizon],
                dtype=np.float32,
            ),
            "force_history_global": self._force_history,
        }
        reflex_results = self._policy.infer(reflex_obs)
        if self._action_key not in reflex_results:
            raise KeyError(f"FRA reflex response requires output key {self._action_key!r}.")
        corrected = np.asarray(reflex_results[self._action_key])
        if corrected.ndim == 2 and corrected.shape[0] == 1:
            corrected = corrected[0]
        if corrected.shape != nominal_action.shape:
            raise ValueError("FRA corrected action must have the same shape as the nominal action.")

        if self._joint_lower_limits is not None and self._joint_upper_limits is not None:
            corrected = corrected.copy()
            corrected[: self._arm_joint_dim] = np.clip(
                corrected[: self._arm_joint_dim],
                self._joint_lower_limits,
                self._joint_upper_limits,
            )

        result = {
            **{key: value for key, value in reflex_results.items() if key not in {self._action_key, "fra"}},
            self._action_key: corrected,
            "fra": {
                **dict(reflex_results.get("fra", {})),
                "chunk_index": self._cur_step,
                "chunk_progress": self._cur_step / self._action_horizon,
                "plan_count": self._plan_count,
                "nominal_action": nominal_action,
                "corrected_action": corrected,
                "residual": corrected[: self._arm_joint_dim] - nominal_action[: self._arm_joint_dim],
            },
        }

        self._cur_step += 1
        if self._cur_step >= self._action_horizon:
            self._nominal_chunk = None
            self._cur_step = 0
        return result

    @override
    def reset(self) -> None:
        self._policy.reset()
        self._nominal_chunk = None
        self._cur_step = 0
        self._plan_count = 0
        self._force_history = None
